spring:
  profiles:
    active: pro
  datasource:
    driver-calss-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pubNumber
    username: lixing
    password: 123456
  jpa:
   hibernate:
     ddl-auto: update
     show-sql: true